DATOS_INICIALES = (
    {'titulo': 'Veinte poemas de amor', 'autor': 'Pablo Neruda', 'isbn': 'ISBN001', 'precio': 12000.0, 'stock': 15},
    {'titulo': 'La casa de los espíritus', 'autor': 'Isabel Allende', 'isbn': 'ISBN002', 'precio': 18500.0, 'stock': 10},
    {'titulo': 'El viejo que leía novelas de amor', 'autor': 'Luis Sepúlveda', 'isbn': 'ISBN003', 'precio': 14000.0, 'stock': 8},
    {'titulo': 'Ardiente paciencia', 'autor': 'Antonio Skármeta', 'isbn': 'ISBN004', 'precio': 9900.0, 'stock': 20},
    {'titulo': 'La muerte y la doncella', 'autor': 'Ariel Dorfman', 'isbn': 'ISBN005', 'precio': 11000.0, 'stock': 5},
    {'titulo': 'Residencia en la tierra', 'autor': 'Pablo Neruda', 'isbn': 'ISBN006', 'precio': 15000.0, 'stock': 12},
    {'titulo': 'Historia de una gaviota y del gato...', 'autor': 'Luis Sepúlveda', 'isbn': 'ISBN007', 'precio': 13000.0, 'stock': 9},
    {'titulo': 'Más allá del invierno', 'autor': 'Isabel Allende', 'isbn': 'ISBN008', 'precio': 19000.0, 'stock': 7},
    {'titulo': 'Los detectives salvajes', 'autor': 'Roberto Bolaño', 'isbn': 'ISBN009', 'precio': 22000.0, 'stock': 4},
    {'titulo': 'Por la patria', 'autor': 'Diamela Eltit', 'isbn': 'ISBN010', 'precio': 16000.0, 'stock': 6},
    {'titulo': 'Canto general', 'autor': 'Pablo Neruda', 'isbn': 'ISBN011', 'precio': 25000.0, 'stock': 3},
    {'titulo': 'El cuaderno de Maya', 'autor': 'Isabel Allende', 'isbn': 'ISBN012', 'precio': 17500.0, 'stock': 11},
    {'titulo': 'Nombre de perro', 'autor': 'Antonio Skármeta', 'isbn': 'ISBN013', 'precio': 10500.0, 'stock': 14},
    {'titulo': 'Manchas de sangre', 'autor': 'Ariel Dorfman', 'isbn': 'ISBN014', 'precio': 13500.0, 'stock': 8},
    {'titulo': 'El gaucho insufrible', 'autor': 'Roberto Bolaño', 'isbn': 'ISBN015', 'precio': 14500.0, 'stock': 5},
    {'titulo': 'Poema 20', 'autor': 'Pablo Neruda', 'isbn': 'ISBN016', 'precio': 5000.0, 'stock': 25},
    {'titulo': 'Paula', 'autor': 'Isabel Allende', 'isbn': 'ISBN017', 'precio': 15500.0, 'stock': 9},
    {'titulo': 'Yakamarí', 'autor': 'Francisco Coloane', 'isbn': 'ISBN018', 'precio': 11500.0, 'stock': 10},
    {'titulo': 'El camino de Santiago', 'autor': 'Roberto Bolaño', 'isbn': 'ISBN019', 'precio': 18000.0, 'stock': 4},
    {'titulo': 'Lumpérica', 'autor': 'Diamela Eltit', 'isbn': 'ISBN020', 'precio': 17000.0, 'stock': 6},
    {'titulo': 'Crepúsculos', 'autor': 'Mariano Latorre', 'isbn': 'ISBN021', 'precio': 12000.0, 'stock': 8},
    {'titulo': 'Altazor', 'autor': 'Vicente Huidobro', 'isbn': 'ISBN022', 'precio': 16500.0, 'stock': 7},
    {'titulo': 'El obsceno pájaro de la noche', 'autor': 'José Donoso', 'isbn': 'ISBN023', 'precio': 21000.0, 'stock': 3},
    {'titulo': 'La última niebla', 'autor': 'María Luisa Bombal', 'isbn': 'ISBN024', 'precio': 12500.0, 'stock': 9},
    {'titulo': 'Adiós, Munken', 'autor': 'Jorge Edwards', 'isbn': 'ISBN025', 'precio': 14000.0, 'stock': 5},
    {'titulo': 'Un año de vida', 'autor': 'Volodia Teitelboim', 'isbn': 'ISBN026', 'precio': 19500.0, 'stock': 2},
    {'titulo': 'La ciudad de los cesares', 'autor': 'Francisco Coloane', 'isbn': 'ISBN027', 'precio': 13000.0, 'stock': 6},
    {'titulo': 'Miltín 1934', 'autor': 'Juan Emar', 'isbn': 'ISBN028', 'precio': 15000.0, 'stock': 4},
    {'titulo': 'El lugar sin límites', 'autor': 'José Donoso', 'isbn': 'ISBN029', 'precio': 16000.0, 'stock': 5},
    {'titulo': 'Hijo de ladrón', 'autor': 'Manuel Rojas', 'isbn': 'ISBN030', 'precio': 11000.0, 'stock': 12}
)